### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by javierav** [felipediesel/auto_increment#35]
Hi @felipediesel!

I saw that you recently migrated from TravisCI to CircleCI to pass the tests automatically, but this makes contributions to the project difficult since contributors have to set up an account on CircleCI to pass the tests. Would you be interested in migrating to Github Actions? Apart from the fact that their operation is similar, this allows any contributor to have the entire CI working just by forking the project.

If you are interested I can work on a PR!

**Comment by felipediesel** [comment]
@javierav I set it up on #38 

I'll merge it soon
