### ISSUE TITLE
Locking during increment

### ISSUE THREAD

**Issue by michaelachrisco** [felipediesel/auto_increment#6]
We had a situation where we were trying to lock the increment operation to the model. 
It would be nice to auto_lock the incremented field while saving.

**Comment by michaelachrisco** [comment]
Added a solution here: 
https://github.com/michaelachrisco/auto_increment/tree/locking
Still needs to be tested (may not work), and this probably needs to be an optional feature.

**Comment by massayoshi** [comment]
I second that. We are currently using the `before_create :my_method` approach and occasionally we get the:
`Duplicate entry '920326-135' for key 'index_message_replies_on_message_id_and_scoped_id'`

**Comment by michaelachrisco** [comment]
Cool. Let me know if you get any workable tests running. I am swamped with work ATM so this is low priority, but I would love to see if this works.

**Comment by felipediesel** [comment]
@michaelachrisco Lock is a good feature. I will take a look at this. But as you said, it should be an option.

**Comment by michaelachrisco** [comment]
I am going to push up some code tonight that should do optional locking on auto_increment. If you are using my branch I would recommend adding `lock: true` on the auto_incrementable field.

Example:
```Ruby
  auto_increment column: :letter_code,
                 scope: :account_id,
                 initial: 'A',
                 force: true,
                 lock: true

```

**Comment by Chucheen** [comment]
@felipediesel in the code you are only doing 

```
query.lock if lock?
```

when it should be 

```
query = query.lock if lock?
```
